"""FROZEN ruleset 2026.08.1. Generated once from describe_live(); NEVER EDIT.

Rows already in customers' hash chains name this version. Editing anything below
changes what those rows claim their rules were, which is the precise failure that
ruleset provenance exists to prevent. To change a rule, mint a NEW frozen module
and point ruleset.CURRENT_VERSION at it; ruleset.drift() fails the suite if you
edit a rule without doing so.

sha256 over canonical JSON: 2995b7fcc2ac83a09336fdd5047fec893c5ffe3cdd01fbc2c61cb3e7a2ab1ed0
"""

VERSION = "2026.08.1"

DEFINITION = {'pii_detectors': {'credit_card': {'flags': [],
                                   'pattern': '(?<!\\d)(?:\\d[ \\-]?){13,19}(?!\\d)',
                                   'validator': 'luhn'},
                   'email': {'flags': [], 'pattern': '[\\w.\\-]+@[\\w\\-]+\\.\\w+'},
                   'ip_address': {'flags': [],
                                  'pattern': '\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b'},
                   'phone': {'flags': [],
                             'pattern': '(?<!\\d)(?:\\+?\\d{1,3}[ '
                                        '.\\-]?)?\\(?\\d{3}\\)?[ .\\-]?\\d{3}[ '
                                        '.\\-]?\\d{4}(?!\\d)'},
                   'ssn_pattern': {'flags': [],
                                   'pattern': '\\b\\d{3}-\\d{2}-\\d{4}\\b'}},
 'policy_map': {'aliases': {'gdpr_basic': 'gdpr', 'hipaa_basic': 'hipaa'},
                'baseline': ['injection', 'secrets'],
                'extra': {'default': [],
                          'gdpr': ['pii'],
                          'hipaa': ['phi'],
                          'soc2': []}},
 'presidio_signals': 'namespaced presidio:* — optional external model, NOT covered by '
                     'this hash or this version',
 'prompt_rules': {'injection': {'injection.dan': {'flags': [],
                                                  'pattern': '\\bDAN\\b',
                                                  'signal': 'prompt_injection'},
                                'injection.ignore_previous': {'flags': ['IGNORECASE'],
                                                              'pattern': 'ignore\\s+(?:all\\s+|any\\s+)?(?:previous|prior|earlier|above|preceding)\\s+(?:instructions?|prompts?|messages?|directions?|context)',
                                                              'signal': 'prompt_injection'},
                                'injection.jailbreak': {'flags': ['IGNORECASE'],
                                                        'pattern': '\\b(?:do\\s+anything\\s+now|jailbreak|developer\\s+mode|unfiltered\\s+mode)\\b',
                                                        'signal': 'prompt_injection'},
                                'injection.override_instructions': {'flags': ['IGNORECASE'],
                                                                    'pattern': '(?:disregard|forget|override|bypass|discard)\\s+(?:all\\s+|your\\s+|the\\s+|any\\s+)?(?:previous\\s+|prior\\s+|above\\s+|safety\\s+|system\\s+)?(?:instructions?|rules?|guidelines?|guardrails?|filters?|restrictions?|policy|policies)',
                                                                    'signal': 'prompt_injection'},
                                'injection.reveal_system_prompt': {'flags': ['IGNORECASE'],
                                                                   'pattern': '(?:reveal|show|print|repeat|display|expose|leak|disclose|tell)\\s+(?:me\\s+)?(?:your\\s+|the\\s+)?(?:system|initial|original|developer|hidden|secret)\\s+(?:prompt|message|instructions?)',
                                                                   'signal': 'prompt_injection'}},
                  'secret': {'secret.aws_access_key': {'flags': [],
                                                       'pattern': '\\bAKIA[0-9A-Z]{16}\\b',
                                                       'signal': 'secret_key'},
                             'secret.bearer_token': {'flags': ['IGNORECASE'],
                                                     'pattern': '\\bbearer\\s+[A-Za-z0-9._\\-]{20,}',
                                                     'signal': 'secret_key'},
                             'secret.openai_key': {'flags': [],
                                                   'pattern': '\\bsk-[A-Za-z0-9_\\-]{16,}\\b',
                                                   'signal': 'secret_key'},
                             'secret.private_key': {'flags': [],
                                                    'pattern': '-----BEGIN [A-Z '
                                                               ']*PRIVATE KEY-----',
                                                    'signal': 'secret_key'}}},
 'reason': {'labels': {'injection': 'prompt_injection',
                       'phi': 'phi',
                       'pii': 'pii',
                       'response_markup': 'unsafe_markup',
                       'response_phi': 'phi',
                       'response_pii': 'pii',
                       'response_scan': 'scan_coverage',
                       'response_secret': 'secret_key',
                       'response_sql': 'unsafe_sql',
                       'response_url': 'unsafe_url',
                       'secret': 'secret_key'},
            'priority': ['secret',
                         'response_secret',
                         'injection',
                         'response_markup',
                         'response_sql',
                         'response_url',
                         'phi',
                         'response_phi',
                         'pii',
                         'response_pii',
                         'response_scan']},
 'response_rules': {'always': {'response_markup.data_html_uri': {'flags': ['IGNORECASE'],
                                                                 'pattern': 'data:\\s*text/html',
                                                                 'signal': 'unsafe_markup'},
                               'response_markup.event_handler': {'flags': ['IGNORECASE'],
                                                                 'pattern': '<\\s*[a-z][^<>]{0,512}\\son[a-z]{3,15}\\s*=',
                                                                 'signal': 'unsafe_markup'},
                               'response_markup.iframe': {'flags': ['IGNORECASE'],
                                                          'pattern': '<\\s*iframe[\\s/>]',
                                                          'signal': 'unsafe_markup'},
                               'response_markup.javascript_uri': {'flags': ['IGNORECASE'],
                                                                  'pattern': '(?:href|src|action|formaction)\\s*=\\s*[\\"\']?\\s*javascript\\s*:',
                                                                  'signal': 'unsafe_markup'},
                               'response_markup.script_tag': {'flags': ['IGNORECASE'],
                                                              'pattern': '<\\s*script[\\s/>]',
                                                              'signal': 'unsafe_markup'},
                               'response_secret.aws_access_key': {'flags': [],
                                                                  'pattern': '\\bAKIA[0-9A-Z]{16}\\b',
                                                                  'signal': 'secret_key'},
                               'response_secret.bearer_token': {'flags': ['IGNORECASE'],
                                                                'pattern': '\\bbearer\\s+[A-Za-z0-9._\\-]{20,}',
                                                                'signal': 'secret_key'},
                               'response_secret.openai_key': {'flags': [],
                                                              'pattern': '\\bsk-[A-Za-z0-9_\\-]{16,}\\b',
                                                              'signal': 'secret_key'},
                               'response_secret.private_key': {'flags': [],
                                                               'pattern': '-----BEGIN '
                                                                          '[A-Z '
                                                                          ']*PRIVATE '
                                                                          'KEY-----',
                                                               'signal': 'secret_key'},
                               'response_sql.destructive': {'flags': ['IGNORECASE'],
                                                            'pattern': '\\b(?:drop\\s+(?:table|database|schema)|truncate\\s+table|delete\\s+from|alter\\s+table)\\b',
                                                            'signal': 'unsafe_sql'},
                               'response_sql.stacked_statement': {'flags': ['IGNORECASE'],
                                                                  'pattern': ';\\s*(?:drop|delete|update|insert|truncate|alter)\\b',
                                                                  'signal': 'unsafe_sql'},
                               'response_sql.tautology': {'flags': ['IGNORECASE'],
                                                          'pattern': '\\bor\\s+(?:1\\s*=\\s*1|\'1\'\\s*=\\s*\'1\'|\\"1\\"\\s*=\\s*\\"1\\")',
                                                          'signal': 'unsafe_sql'},
                               'response_url.file_scheme': {'flags': ['IGNORECASE'],
                                                            'pattern': '\\bfile://',
                                                            'signal': 'unsafe_url'},
                               'response_url.private_host': {'flags': ['IGNORECASE'],
                                                             'pattern': 'https?://(?:localhost|127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|0\\.0\\.0\\.0|10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|192\\.168\\.\\d{1,3}\\.\\d{1,3}|172\\.(?:1[6-9]|2\\d|3[01])\\.\\d{1,3}\\.\\d{1,3}|169\\.254\\.\\d{1,3}\\.\\d{1,3}|\\[::1\\]|metadata\\.google\\.internal)',
                                                             'signal': 'unsafe_url'}},
                    'carry_chars': 256,
                    'personal_by_policy': {'gdpr': 'response_pii',
                                           'hipaa': 'response_phi'}},
 'schema': 'foxy-ruleset-v1'}
